//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoDispositivos.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestaoDispositivos.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Data é obrigatória.
        /// </summary>
        public static string Date_Not_Empty {
            get {
                return ResourceManager.GetString("Date_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha tem que ser igual a senha atual.
        /// </summary>
        public static string Different_Password {
            get {
                return ResourceManager.GetString("Different_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID do dispositivo é obrigatório.
        /// </summary>
        public static string Dispositivo_Id_Not_Empty {
            get {
                return ResourceManager.GetString("Dispositivo_Id_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dispositivo não encontrado.
        /// </summary>
        public static string Dispositivo_Not_Found {
            get {
                return ResourceManager.GetString("Dispositivo_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já existente.
        /// </summary>
        public static string Email_Exists {
            get {
                return ResourceManager.GetString("Email_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esse tipo de email é inválido, lembre-se de incluir esse modelo email@email.com.
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email é obrigatório.
        /// </summary>
        public static string Email_Not_Empty {
            get {
                return ResourceManager.GetString("Email_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O IMEI tem que conter 15 caracteres.
        /// </summary>
        public static string IMEI_Not_Empty {
            get {
                return ResourceManager.GetString("IMEI_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email ou senha inválidos.
        /// </summary>
        public static string Invalid_Login {
            get {
                return ResourceManager.GetString("Invalid_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome é obrigatório.
        /// </summary>
        public static string Name_Not_Empty {
            get {
                return ResourceManager.GetString("Name_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha tem que conter 8 caracteres, que contenham letras maiúsculas, minísculas, número e caracteres especiais  .
        /// </summary>
        public static string Password_Invalid {
            get {
                return ResourceManager.GetString("Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Serial tem que conter no mínimo 50 caracteres.
        /// </summary>
        public static string Serial_Not_Empty {
            get {
                return ResourceManager.GetString("Serial_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Status precisa ser true ou false.
        /// </summary>
        public static string Status_Invalid {
            get {
                return ResourceManager.GetString("Status_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo inválido.
        /// </summary>
        public static string Type_Invalid {
            get {
                return ResourceManager.GetString("Type_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido.
        /// </summary>
        public static string Unknow_Error {
            get {
                return ResourceManager.GetString("Unknow_Error", resourceCulture);
            }
        }
    }
}
